resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: gpdb_src
    type: pull-request
    source:
      repository: berlin-ab/gpdb
      access_token: {{gpdb-git-access-token}}
      ignore_paths:
      - gpdb-doc/*
      - README*

  - name: ubuntu-gpdb-dev-16
    type: docker-image
    source:
      repository: pivotaldata/ubuntu-gpdb-dev
      tag: '16.04'

      
anchors:
  - &pr_failure
    put: report_pr_failure
    resource: gpdb_src
    params:
      path: gpdb_src
      status: failure
      
  - &pr_pending
    put: report_pr_pending
    resource: gpdb_src
    params:
      path: gpdb_src
      status: pending
      
  - &pr_success
    put: report_pr_success
    resource: gpdb_src
    params:
      path: gpdb_src
      status: success
      
tasks:
  - &icw
    task: icw
    image: image
    file: gpdb_src/concourse/tasks/new/icw.yml
    timeout: 3h
    on_failure: *pr_failure
    
  - &icw_orca
    <<: *icw
    params:
      CONFIGURE_FLAGS: --enable-orca
    
  - &icw_planner
    <<: *icw
    params:
      CONFIGURE_FLAGS: --disable-orca

  
jobs:
  - name: compile_and_test_gpdb
    public: true
    max_in_flight: 10
    plan:
    - aggregate:
      - get: gpdb_src
        trigger: true
        version: every
      - get: image
        resource: ubuntu-gpdb-dev-16

    - *pr_pending

    - aggregate:
        - *icw_orca
        - *icw_planner

    - *pr_success
