## ======================================================================
## resources
## ======================================================================

resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

  - name: gcs
    type: docker-image
    source:
      repository: frodenas/gcs-resource

resources:
  - name: gpdb_pr
    type: pull-request
    source:
      repository: greenplum-db/gpdb
      access_token: ((gpdb-git-access-token))
      base_branch: "5X_STABLE"
      ignore_paths:
        - gpdb-doc/*
        - README*

  - name: centos-gpdb-dev-6
    type: docker-image
    source:
      repository: pivotaldata/centos-gpdb-dev
      tag: '6-gcc6.2-llvm3.7'

jobs:
  - name: compile_and_test_gpdb
    public: true
    max_in_flight: 4
    plan:
    - aggregate:
      - get: gpdb_pr
        trigger: true
        version: every
      - get: centos-gpdb-dev-6

    - put: gpdb_pr
      params:
        path: gpdb_pr
        status: pending

    - task: compile_gpdb_open_source_centos6
      file: gpdb_pr/concourse/tasks/compile_gpdb_open_source_centos.yml
      image: centos-gpdb-dev-6
      input_mapping:
        gpdb_src: gpdb_pr
      params:
        CONFIGURE_FLAGS: {{configure_flags}}
      on_failure: &pr_failure
        put: gpdb_pr
        params:
          path: gpdb_pr
          status: failure
      timeout: 30m

    - aggregate:
      - task: icw_planner_centos6
        file: gpdb_pr/concourse/tasks/ic_gpdb.yml
        image: centos-gpdb-dev-6
        input_mapping:
          gpdb_src: gpdb_pr
          bin_gpdb: gpdb_artifacts
        params:
          MAKE_TEST_COMMAND: PGOPTIONS='-c optimizer=off' installcheck-world
          BLDWRAP_POSTGRES_CONF_ADDONS: "fsync=off"
          TEST_OS: centos
          CONFIGURE_FLAGS: {{configure_flags}}
        timeout: 1h
        on_failure: *pr_failure

      - task: icw_gporca_orca_centos6
        file: gpdb_pr/concourse/tasks/ic_gpdb.yml
        image: centos-gpdb-dev-6
        input_mapping:
          gpdb_src: gpdb_pr
          bin_gpdb: gpdb_artifacts
        params:
          MAKE_TEST_COMMAND: PGOPTIONS='-c optimizer=on' installcheck-world
          BLDWRAP_POSTGRES_CONF_ADDONS: "fsync=off"
          TEST_OS: centos
          CONFIGURE_FLAGS: {{configure_flags}}
        timeout: 2h30m
        on_failure: *pr_failure

    - put: report_pr_success
      resource: gpdb_pr
      params:
        path: gpdb_pr
        status: success
