resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

  - name: gcs
    type: docker-image
    source:
      repository: frodenas/gcs-resource

resources:
  - name: gpdb_pr
    type: pull-request
    source:
      repository: berlin-ab/gpdb
      access_token: ((gpdb-git-access-token))
      base_branch: "5X_STABLE"
      ignore_paths:
        - gpdb-doc/*
        - README*

  - name: centos-gpdb-dev-6
    type: docker-image
    source:
      repository: pivotaldata/centos-gpdb-dev
      tag: '6-gcc6.2-llvm3.7'

jobs:
  - name: compile_and_test_gpdb
    public: true
    max_in_flight: 4
    plan:
    - aggregate:
      - get: gpdb_pr
        trigger: true
        version: every
      - get: centos-gpdb-dev-6

    - put: gpdb_pr
      params:
        path: gpdb_pr
        status: pending

    - aggregate:
      - task: compile-and-run-tests-planner
        file: gpdb_pr/concourse/tasks/run-pr-pipeline.yml
        image: centos-gpdb-dev-6
        input_mapping:
          gpdb_src: gpdb_pr
        params:
          MAKE_TEST_COMMAND: PGOPTIONS='-c optimizer=off' installcheck-world
          TEST_OS: centos
        on_failure: &pr_failure
          put: gpdb_pr
          params:
            path: gpdb_pr
            status: failure
        timeout: 30m

      - task: compile-and-run-tests-orca
        file: gpdb_pr/concourse/tasks/run-pr-pipeline.yml
        image: centos-gpdb-dev-6
        input_mapping:
          gpdb_src: gpdb_pr
        params:
          MAKE_TEST_COMMAND: PGOPTIONS='-c optimizer=on' installcheck-world
          TEST_OS: centos
        on_failure: &pr_failure
          put: gpdb_pr
          params:
            path: gpdb_pr
            status: failure
        timeout: 30m

    - put: report_pr_success
      resource: gpdb_pr
      params:
        path: gpdb_pr
        status: success
