os:
  - linux

services:
  - docker

before_install:
  - docker pull pivotaldata/greenplum-server-ubuntu-18

script:
  - docker run -v ${PWD}:/gpdb_src --rm pivotaldata/greenplum-server-ubuntu-18 cd gpdb_src; MAKE_TASK='-C src/test/regress installcheck' ./concourse/pr_pipeline/runner.bash
