resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: gpdb_src
    type: pull-request
    source:
      repository: berlin-ab/gpdb
      access_token: {{berlin-gpdb-git-access-token}}
      ignore_paths:
      - gpdb-doc/*
      - README*

  - name: docker-image
    type: docker-image
    source:
      repository: adamberlinpivotal/ubuntu-18-gpdb
      tag: latest
      
anchors:
  - &pr_failure
    put: report_pr_failure
    resource: gpdb_src
    params:
      path: gpdb_src
      status: failure
      
  - &pr_pending
    put: report_pr_pending
    resource: gpdb_src
    params:
      path: gpdb_src
      status: pending
      
  - &pr_success
    put: report_pr_success
    resource: gpdb_src
    params:
      path: gpdb_src
      status: success

  - &fetch_pr
    get: gpdb_src
    trigger: true
    version: every
    on_failure: *pr_failure

  - &fetch_image
    get: image
    resource: docker-image
    on_failure: *pr_failure

tasks:
  - &task
    image: image
    file: gpdb_src/concourse/pr_pipeline/task.yml
    timeout: 3h
    on_failure: *pr_failure
        
  - &icw_orca
    <<: *task
    task: icw_orca
    params:
      MAKE_TASK: installcheck-world
      CONFIGURE_FLAGS: --without-zstd
      PGOPTIONS: '-c optimizer=on'
    
  - &icw_planner
    <<: *task
    task: icw_planner
    params:
      MAKE_TASK: installcheck-world
      CONFIGURE_FLAGS: --without-zstd
      PGOPTIONS: '-c optimizer=off'

  - &icw_orca_without_asserts
    <<: *task
    task: icw_orca_without_asserts
    params:
      MAKE_TASK: installcheck-world
      CONFIGURE_FLAGS: --without-zstd --disable-cassert
      PGOPTIONS: '-c optimizer=on'

  - &icw_planner_without_asserts
    <<: *task
    task: icw_planner_without_asserts
    params:
      MAKE_TASK: installcheck-world
      CONFIGURE_FLAGS: --without-zstd --disable-cassert
      PGOPTIONS: '-c optimizer=off'

  - &test_gpload
    <<: *task
    task: test_gpload
    params:
      MAKE_TASK: -C gpMgmt/bin installcheck

  - &test_regress
    <<: *task
    task: test_regress
    params:
      CONFIGURE_FLAGS: --without-zstd
      PGOPTIONS: '-c optimizer=off'
      MAKE_TASK: -C src/test/regress installcheck

  - &test_isolation2
    <<: *task
    task: test_isolation2
    params:
      CONFIGURE_FLAGS: --without-zstd
      PGOPTIONS: '-c optimizer=off'
      MAKE_TASK: -C src/test/isolation2 installcheck

  - &test_src_bin
    <<: *task
    task: test_src_bin
    params:
      CONFIGURE_FLAGS: --without-zstd
      PGOPTIONS: '-c optimizer=off'
      MAKE_TASK: -c src/bin installcheck

  - &test_unit
    <<: *task
    task: test_unit
    params:
      CONFIGURE_FLAGS: --without-zstd
      PGOPTIONS: '-c optimizer=off'
      MAKE_TASK: unittest-check
        
jobs:
  - name: compile_and_test_gpdb
    public: true
    max_in_flight: 10
    plan:
    - aggregate:
      - *fetch_pr
      - *fetch_image

    - *pr_pending

    - aggregate:
        - *icw_planner
        - *icw_orca
        - *icw_planner_without_asserts
        - *icw_orca_without_asserts
        - *test_gpload
        - *test_regress
        - *test_isolation2
        - *test_src_bin
        - *test_unit

    - *pr_success
